-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "update_id" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "update_id" SET DATA TYPE TIMESTAMP(3);
